export const AUTH_USER = "AUTH_USER";
export const RECIEVE_USER = "RECIEVE_USER";
export const RECIEVE_QUESTIONS = "RECIEVE_QUESTIONS";
export const ADD_ANSWER_TO_QUESTION = "ADD_ANSWER_TO_QUESTION";
export const ADD_ANSWER_TO_USER = "ADD_ANSWER_TO_USER";
export const ADD_QUESTION_TO_USER = "ADD_QUESTION_TO_USER";
export const ADD_QUESTION_TO_QUESTION = "ADD_QUESTION_TO_QUESTION";
